networks:
  sshbridge:
    driver: bridge
services:
  server:
    restart: unless-stopped
    image: ${IMAGE:-dbndev/ssh-bridge}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./authorized_keys:/home/debian/.ssh/authorized_keys
      - /workspaces:/workspaces
      - ${PWD}:${PWD}:cached
      - /dev:/dev
      - vscode:/vscode
    working_dir: ${PWD}
    ports:
      - ${VEGITO_SSH_BRIDGE_PORT:-22022}:22
      - ${VEGITO_DOCKER_BRIDGE_PORT:-23750}:2375
    container_name: ssh-server
    environment:
      SSH_PUBLIC_KEY: /home/debian/.ssh/authorized_keys
      VSCODE_SERVER_COMMIT: ${VSCODE_SERVER_COMMIT:-93cfdd489c3b228840d0f86ec77c3636277c93ea}
      VSCODE_SERVER_ARCH: ${VSCODE_SERVER_ARCH}

      VEGITO_DOCKER_REGISTRIES: ${VEGITO_DOCKER_REGISTRIES}
      VEGITO_DOCKERHUB_PAT: ${VEGITO_DOCKERHUB_PAT}
      VEGITO_DOCKER_REGISTRY_MODE: ${VEGITO_DOCKER_REGISTRY_MODE}
      VEGITO_STRIPE_DEBUG_KEY: ${VEGITO_STRIPE_DEBUG_KEY}
      VEGITO_PROJECT_USER: ${VEGITO_PROJECT_USER}
      VEGITO_DOCKER_COMPOSE_HOST: ${VEGITO_DOCKER_COMPOSE_HOST}
      VEGITO_DOCKERHUB_USERNAME: ${VEGITO_DOCKERHUB_USERNAME}
      VEGITO_DNS_SERVER: ${VEGITO_DNS_SERVER:-1.1.1.1}

    networks:
      sshbridge:
        aliases:
          - proxy

  docker-proxy:
    image: ${IMAGE:-dbndev/ssh-bridge}
    ports:
      - 23750:23750
    volumes:
      - ${SSH_PRIVATE_KEY:-${PWD}/id_rsa}:/home/debian/.ssh/id_rsa
    environment:
      DOCKER_HOST: 0.0.0.0:23750
      SSH_DOCKER_SERVER: ${SSH_DOCKER_SERVER:-server:22}
      SSH_DOCKER_SERVER_HOST: ${SSH_DOCKER_SERVER_HOST:-server}
      SSH_DOCKER_SERVER_PORT: ${SSH_DOCKER_SERVER_PORT:-22}
      HOME: /home/debian
    command: |
      bash -c '
      set -eu
      trap "echo Exited entrypoint with code $$?." EXIT
      until nc -z $${SSH_DOCKER_SERVER_HOST} $${SSH_DOCKER_SERVER_PORT} 2>/dev/null ; do
        echo waitind docker server host at $${SSH_DOCKER_SERVER_HOST}:$${SSH_DOCKER_SERVER_PORT}...
        sleep 1
      done
      ssh-keyscan -H -p $${SSH_DOCKER_SERVER_PORT} $${SSH_DOCKER_SERVER_HOST} >> ~/.ssh/known_hosts
      echo creating ssh docker tunnel
      chmod 600 $${SSH_PRIVATE_KEY:-$${HOME}/.ssh/id_rsa}
      echo "ssh -i $${SSH_PRIVATE_KEY:-$${HOME}/.ssh/id_rsa} -NL 0.0.0.0:23750:/var/run/docker.sock $${USER}@$${SSH_DOCKER_SERVER_HOST} -p $${SSH_DOCKER_SERVER_PORT} &"
      ssh -i $${SSH_PRIVATE_KEY:-$${HOME}/.ssh/id_rsa} -NL 0.0.0.0:23750:/var/run/docker.sock $${USER}@$${SSH_DOCKER_SERVER_HOST} -p $${SSH_DOCKER_SERVER_PORT} &
      until nc -z localhost 23750 2>/dev/null ; do
        echo waitind ssh docker tunnel...
        sleep 1
      done
      echo ssh docker tunnel up
      while true ; do sleep 1000 ; done
      '
    container_name: docker-proxy
    networks:
      sshbridge:
        aliases:
          - proxy

  consumer:
    image: ${IMAGE:-dbndev/ssh-bridge}
    environment:
      - DOCKER_HOST=docker-proxy:23750
    command: |
      bash -c "
      until docker version; do echo Waiting docker over client provider; done
      "
    container_name: consumer
    networks:
      sshbridge:
        aliases:
          - consumer
volumes:
  vscode:
    external: true
    name: vscode
